### ISSUE TITLE
Audio doesn't record + setting to send text alongside it is broken.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [MKSx/Send-Audio-Plugin-BetterDiscord#3]
1. No audio being recorded.
2. If "Send text message along with audio" is enabled the .ogg file is not sent regardless.

I'm not JS savvy, though I wish I could help.
Other than that, the idea of the plugin is wonderful! Keep making these wonderful ideas!

**Comment by MKSx** [comment]
Hello, I apologize for the delay in answering you

The second problem I ended up identifying, unfortunately discord made changes to the messaging system which eventually broke this plugin functionality.

Already the first problem could not detect, I ask you to open the discord console using ctrl + shift + i on windows or Cmd + Opt + i on mac

Check if there are any error messages involving the plugin, this may help in identifying the problem.

Thank you very much for reporting the issue, if you wish you can call me on discord personally Matues # 4441

I will temporarily disable the sending of messages along with the audio until I get an ideal solution to the problem.

Thanks and sorry for my english
