### ISSUE TITLE
[Enhancement] Add pause functionality

### ISSUE THREAD

**Issue by l0c4lh057** [MKSx/Send-Audio-Plugin-BetterDiscord#6]
Don't just add a send and a stop button but also a button to pause the record. Then you can resume after some time again.

**Comment by MKSx** [comment]
I was already working on an update with this, some adjustments and tests are missing to see possible problems.

With this it will be possible to start recording the audio in one channel and continue in another server / channel, but only being able to send the audio where the recording started.

![image](https://user-images.githubusercontent.com/17793927/73769589-b0acd680-4759-11ea-9189-f3960e3fc5af.png)

![image](https://user-images.githubusercontent.com/17793927/73769717-e3ef6580-4759-11ea-939b-58f232e0e2e9.png)

https://i.imgur.com/FyL4MH4.mp4

**Comment by MKSx** [comment]
It's a good idea, I will do this to come up with the next update
