### ISSUE TITLE
XSS in recordingInfoPanel

### ISSUE THREAD

**Issue by quantiom** [MKSx/Send-Audio-Plugin-BetterDiscord#8]
### Issue
On line 1072, `data` is declared as: 
```const data = `Recording in ${SendAudioUtil.getChannelName(type)} (${SendAudioUtil.getGuildName(type)})`;```
And the `getChannelName` / `getGuildName` does not sanitize the name.
`data` is used to create the `SendAudioUtil` panel and is not sanitized either.
If you want to test this, you can rename a guild or channel to `<img src=x onerror=alert(1)>` and click the record button.

### Result: 
![Result](https://i.imgur.com/K2BNb4U.png)

**Comment by MKSx** [comment]
Thanks, I got this last update
